version: '3.1'

services:
  api-server:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/go/src/app
    tty: true
    ports:
      - 8080:8080
    environment:
      - GO_ENV='${GO_ENV}'
      - MYSQL_PASSWORD='${MYSQL_PASSWORD}'
      
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql